#!/bin/sh

cat <<'EOF'
In this task, you need to find the hidden flag in a text file 'cipher.txt'.

To decode the flag, please do the following three operations in order:
  1) Remove all the occurrences of '[33m[[0m'.
  2) Replace all the occurrences of '[33mpr[0m' (only lowercase) to '[33mIN[0m'.
  3) Remove all the occurrences of '[33m][0m'.
  4) Replace all the occurrences of '[33mqu[0m' (regardless uppercase or lowercase) to '[33mst[0m'.
  5) After these steps, find your flag!
EOF
