#!/bin/sh

cat <<'EOF'
In this task, you are given a git repository named 'Ripes' in zip form (Ripes.zip).

We want you compute some statistics of this project.
  1) First, we only consider files in '[33m./src[0m' directory.
  2) Then we need to screen (filter) only CPP files (*.cpp, *.h), not others (e.g., *.json, *.txt, *.ui).
  3) After that please take files that is greater than 3 KiB (3072 B).
  4) Over all these files, please compute the [1;33mtotal line number[0m (add up).

In the end, if the sum of line number is equal to [32m<X>[0m, the flag is 'sast2023{[32m<X>[0m-LINES-IN-TOTAL}',
  [37me.g., if the total line number is equal to 1024, the flag will be 'sast2023{1024-LINES-IN-TOTAL}'[0m.
EOF
